export const LOGIN = '@SETTINGS/LOGIN';
export const FETCH_REQUEST = '@SETTINGS/FETCH_REQUEST';
export const FETCH_SUCCESS = '@SETTINGS/FETCH_SUCCESS';
export const FETCH_FAIL = '@SETTINGS/FETCH_FAIL';
